import { Listing, AuditEvent } from './types';

export const mockListings: Listing[] = [
  {
    id: 'TCN-2025-001',
    name: 'Clearwater Solar Farm Development',
    sector: 'Renewable Energy',
    status: 'approved',
    submittedAt: '2025-01-08',
    updatedAt: '2025-01-12',
    submitterId: 'sub-001',
    submitterName: 'Greenfield Capital Partners',
    description:
      'A utility-scale solar photovoltaic development project spanning 2,400 acres in west Texas. The project seeks collaboration partners for land acquisition coordination, permitting support, and operational co-development. All financial arrangements are determined externally and independently between participants.',
    targetAmount: 24000000,
    location: 'Midland, Texas, USA',
    timeline: 'Q2 2025 – Q4 2026',
    highlights: [
      '240 MW installed capacity',
      'PPA framework in place',
      'Permitting at 70% completion',
      'Grid interconnection approved',
    ],
    signalCount: 14,
  },
  {
    id: 'TCN-2025-002',
    name: 'Coastal Mixed-Use Redevelopment',
    sector: 'Real Estate',
    status: 'approved',
    submittedAt: '2025-01-14',
    updatedAt: '2025-01-19',
    submitterId: 'sub-002',
    submitterName: 'Harbor View Development LLC',
    description:
      'Mixed-use waterfront redevelopment project in the Port of Charleston area. Conversion of 12 decommissioned warehouse structures into residential lofts, commercial retail, and hospitality venues. Seeking collaboration partners for phased development planning and coordination.',
    targetAmount: 18500000,
    location: 'Charleston, South Carolina, USA',
    timeline: 'Q3 2025 – Q2 2028',
    highlights: [
      '380,000 sq ft total area',
      'Historic preservation credits secured',
      'Zoning pre-approved',
      'Anchor tenant LOI received',
    ],
    signalCount: 9,
  },
  {
    id: 'TCN-2025-003',
    name: 'Permian Basin Enhanced Recovery Initiative',
    sector: 'Energy',
    status: 'approved',
    submittedAt: '2025-01-20',
    updatedAt: '2025-01-24',
    submitterId: 'sub-003',
    submitterName: 'Basin Energy Partners',
    description:
      'Enhanced oil recovery operation utilizing carbon dioxide injection across three established production fields in the Permian Basin. The collaboration opportunity involves operational co-participation in secondary recovery phases. Field-level production data available under NDA.',
    targetAmount: 31000000,
    location: 'Odessa, Texas, USA',
    timeline: 'Q1 2025 – Q3 2027',
    highlights: [
      '4,200 BOE/day current production',
      'CO₂ supply contract executed',
      'Three-field operation',
      'Proven reserves certified',
    ],
    signalCount: 22,
  },
  {
    id: 'TCN-2025-004',
    name: 'Mountain West Data Center Campus',
    sector: 'Technology',
    status: 'approved',
    submittedAt: '2025-01-28',
    updatedAt: '2025-02-03',
    submitterId: 'sub-004',
    submitterName: 'Summit Infrastructure Group',
    description:
      'Tier-3 data center campus development on a 48-acre site in the Denver metropolitan area. The project seeks collaboration partners for phased construction coordination and hyperscale tenant relationship development. 100% renewable-powered by onsite solar and wind offtake agreements.',
    targetAmount: 42000000,
    location: 'Aurora, Colorado, USA',
    timeline: 'Q2 2025 – Q1 2027',
    highlights: [
      '180 MW total power capacity',
      '3 hyperscale LOIs received',
      'LEED Gold target',
      'Carrier-neutral fiber hub',
    ],
    signalCount: 31,
  },
  {
    id: 'TCN-2025-005',
    name: 'Offshore Wind Coordination Consortium',
    sector: 'Renewable Energy',
    status: 'approved',
    submittedAt: '2025-02-05',
    updatedAt: '2025-02-11',
    submitterId: 'sub-005',
    submitterName: 'Atlantic Wind Ventures',
    description:
      'Consortium formation for collaboration across an 800 MW offshore wind development lease area off the Virginia coast. The project coordinates marine survey, turbine procurement, and port logistics across multiple collaboration tracks. BOEM lease rights in place.',
    targetAmount: 55000000,
    location: 'Virginia Beach, Virginia, USA',
    timeline: 'Q2 2025 – Q4 2029',
    highlights: [
      '800 MW BOEM lease area',
      'Environmental review complete',
      'Port facility agreement signed',
      'Turbine OEM term sheet executed',
    ],
    signalCount: 18,
  },
  {
    id: 'TCN-2025-006',
    name: 'Sunbelt Industrial Logistics Park',
    sector: 'Real Estate',
    status: 'approved',
    submittedAt: '2025-02-12',
    updatedAt: '2025-02-18',
    submitterId: 'sub-002',
    submitterName: 'Harbor View Development LLC',
    description:
      'Development of a 1.2 million square foot Class A industrial logistics facility positioned at the intersection of two major interstate corridors in the Phoenix metropolitan area. Collaboration sought for phased pad development and pre-leasing coordination with 3PL operators.',
    targetAmount: 28000000,
    location: 'Goodyear, Arizona, USA',
    timeline: 'Q3 2025 – Q1 2027',
    highlights: [
      '1.2M sq ft across 4 buildings',
      'Two I-10 interchange access points',
      'BNSF rail spur available',
      '40-foot clear height spec',
    ],
    signalCount: 12,
  },
  {
    id: 'TCN-2025-007',
    name: 'Gulf Coast LNG Terminal Expansion',
    sector: 'Energy',
    status: 'info_requested',
    submittedAt: '2025-02-20',
    updatedAt: '2025-02-20',
    submitterId: 'sub-006',
    submitterName: 'Gulf Energy Terminal LLC',
    description:
      'Expansion of an existing LNG liquefaction and export terminal with the addition of two new processing trains. Collaboration opportunity encompasses engineering coordination, regulatory filing support, and long-term offtake arrangement facilitation with international counterparties.',
    targetAmount: 68000000,
    location: 'Port Arthur, Texas, USA',
    timeline: 'Q3 2025 – Q2 2028',
    highlights: [
      '6 MTPA additional capacity',
      'FERC pre-filing initiated',
      'Asian market offtake discussions',
      'Berth expansion permitted',
    ],
    signalCount: 0,
  },
  {
    id: 'TCN-2025-008',
    name: 'Southeast Semiconductor Fab Site Development',
    sector: 'Technology',
    status: 'pending',
    submittedAt: '2025-02-22',
    updatedAt: '2025-02-22',
    submitterId: 'sub-007',
    submitterName: 'Meridian Advanced Manufacturing LLC',
    description:
      'Greenfield development of a 600,000 sq ft semiconductor fabrication facility in the Research Triangle area of North Carolina. Collaboration partners sought for utility infrastructure coordination, workforce development pipeline, and supply chain localization strategy.',
    targetAmount: 94000000,
    location: 'Durham, North Carolina, USA',
    timeline: 'Q4 2025 – Q3 2029',
    highlights: [
      '600,000 sq ft fab footprint',
      'CHIPS Act pre-application submitted',
      'State incentive MOU signed',
      'Utility power reserved — 400 MW',
    ],
    signalCount: 0,
  },
];

export const mockAuditEvents: AuditEvent[] = [
  {
    id: 'evt-001',
    timestamp: '2025-02-22T16:44:00Z',
    eventType: 'listing_submitted',
    userId: 'sub-007',
    userName: 'Meridian Advanced Manufacturing LLC',
    role: 'submitter',
    details: 'New listing submitted for admin review',
    listingId: 'TCN-2025-008',
  },
  {
    id: 'evt-002',
    timestamp: '2025-02-22T09:12:00Z',
    eventType: 'listing_submitted',
    userId: 'sub-006',
    userName: 'Gulf Energy Terminal LLC',
    role: 'submitter',
    details: 'New listing submitted for admin review',
    listingId: 'TCN-2025-007',
  },
  {
    id: 'evt-002b',
    timestamp: '2025-02-21T14:55:00Z',
    eventType: 'listing_info_requested',
    userId: 'admin-001',
    userName: 'TCN Admin',
    role: 'admin',
    details: 'Additional information requested from submitter — project description requires clarification',
    listingId: 'TCN-2025-007',
  },
  {
    id: 'evt-003',
    timestamp: '2025-02-18T14:30:00Z',
    eventType: 'listing_approved',
    userId: 'admin-001',
    userName: 'TCN Admin',
    role: 'admin',
    details: 'Listing approved and published to registry',
    listingId: 'TCN-2025-006',
  },
  {
    id: 'evt-004',
    timestamp: '2025-02-17T11:05:00Z',
    eventType: 'interest_signaled',
    userId: 'part-003',
    userName: 'Participant #3',
    role: 'participant',
    details: 'Interest signaled in Sunbelt Industrial Logistics Park',
    listingId: 'TCN-2025-006',
  },
  {
    id: 'evt-005',
    timestamp: '2025-02-16T09:44:00Z',
    eventType: 'interest_signaled',
    userId: 'part-007',
    userName: 'Participant #7',
    role: 'participant',
    details: 'Interest signaled in Mountain West Data Center Campus',
    listingId: 'TCN-2025-004',
  },
  {
    id: 'evt-006',
    timestamp: '2025-02-11T16:20:00Z',
    eventType: 'listing_approved',
    userId: 'admin-001',
    userName: 'TCN Admin',
    role: 'admin',
    details: 'Listing approved and published to registry',
    listingId: 'TCN-2025-005',
  },
  {
    id: 'evt-007',
    timestamp: '2025-02-10T13:15:00Z',
    eventType: 'listing_info_requested',
    userId: 'admin-001',
    userName: 'TCN Admin',
    role: 'admin',
    details: 'Additional information requested from submitter',
    listingId: 'TCN-2025-005',
  },
  {
    id: 'evt-008',
    timestamp: '2025-02-05T10:00:00Z',
    eventType: 'listing_submitted',
    userId: 'sub-005',
    userName: 'Atlantic Wind Ventures',
    role: 'submitter',
    details: 'New listing submitted for admin review',
    listingId: 'TCN-2025-005',
  },
  {
    id: 'evt-009',
    timestamp: '2025-02-03T15:45:00Z',
    eventType: 'listing_approved',
    userId: 'admin-001',
    userName: 'TCN Admin',
    role: 'admin',
    details: 'Listing approved and published to registry',
    listingId: 'TCN-2025-004',
  },
  {
    id: 'evt-010',
    timestamp: '2025-01-31T11:20:00Z',
    eventType: 'user_login',
    userId: 'part-012',
    userName: 'Participant #12',
    role: 'participant',
    details: 'Platform access authenticated',
  },
  {
    id: 'evt-011',
    timestamp: '2025-01-30T09:05:00Z',
    eventType: 'interest_signaled',
    userId: 'part-001',
    userName: 'Participant #1',
    role: 'participant',
    details: 'Interest signaled in Permian Basin Enhanced Recovery Initiative',
    listingId: 'TCN-2025-003',
  },
  {
    id: 'evt-012',
    timestamp: '2025-01-24T14:10:00Z',
    eventType: 'listing_approved',
    userId: 'admin-001',
    userName: 'TCN Admin',
    role: 'admin',
    details: 'Listing approved and published to registry',
    listingId: 'TCN-2025-003',
  },
  {
    id: 'evt-013',
    timestamp: '2025-01-19T10:30:00Z',
    eventType: 'listing_approved',
    userId: 'admin-001',
    userName: 'TCN Admin',
    role: 'admin',
    details: 'Listing approved and published to registry',
    listingId: 'TCN-2025-002',
  },
  {
    id: 'evt-014',
    timestamp: '2025-01-12T09:00:00Z',
    eventType: 'listing_approved',
    userId: 'admin-001',
    userName: 'TCN Admin',
    role: 'admin',
    details: 'Listing approved and published to registry',
    listingId: 'TCN-2025-001',
  },
  {
    id: 'evt-015',
    timestamp: '2025-01-08T08:30:00Z',
    eventType: 'listing_submitted',
    userId: 'sub-001',
    userName: 'Greenfield Capital Partners',
    role: 'submitter',
    details: 'New listing submitted for admin review',
    listingId: 'TCN-2025-001',
  },
];

export const approvedListings = mockListings.filter((l) => l.status === 'approved');
export const pendingListings = mockListings.filter((l) => l.status === 'pending' || l.status === 'info_requested');
